import Image from 'next/image';

export const metadata = {
  title: 'Thankyou',
  description: 'Generated by create next app',
};

export default function ThankyouPage() {
  return (
    <div
      style={{
        fontSize: '24px',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        paddingTop: '50px',
        paddingBottom: '50px',
      }}
    >
      Thank you for your order
      <Image
        src="/thank-you.png"
        width={300}
        height={300}
        style={{ marginTop: '60px' }}
        alt="thank-you-page"
      />
    </div>
  );
}
