import { cache } from 'react';
import { sql } from './connect';

export const metadata = {
  title: 'Products',
  description: 'Generated by create next app',
};

const products = [
  {
    id: 1,
    imgSrc: '/speaker-1.png',
    productName: 'Portable Wireless Blootooth Speaker',
    productPrice: 77,
  },
  {
    id: 2,
    imgSrc: '/speaker-2.png',
    productName: 'Portable Wireless Mini Blootooth Speaker',
    productPrice: 57,
  },
  {
    id: 3,
    imgSrc: '/headphones-1.png',
    productName: 'Wireless Foldable Bluetooth Headphones',
    productPrice: 40,
  },
  {
    id: 4,
    imgSrc: '/headphones-2.png',
    productName: 'Foldable Wireless Bluetooth Headset',
    productPrice: 52,
  },
  {
    id: 5,
    imgSrc: '/mouse.png',
    productName: 'Portable Wireless Gaming Mouse',
    productPrice: 30,
  },
  {
    id: 6,
    imgSrc: '/keyboard.png',
    productName: 'Portable Wireless Keyboard',
    productPrice: 80,
  },
  {
    id: 7,
    imgSrc: '/portable-monitor.png',
    productName: 'Wireless Monitor HD Resolution',
    productPrice: 140,
  },
  {
    id: 8,
    imgSrc: '/power-bank.png',
    productName: 'Portable Power Bank Charger',
    productPrice: 90,
  },
  {
    id: 9,
    imgSrc: '/speaker-1.png',
    productName: 'Portable Wireless Blootooth Speaker',
    productPrice: 77,
  },
  {
    id: 10,
    imgSrc: '/speaker-2.png',
    productName: 'Portable Wireless Mini Blootooth Speaker',
    productPrice: 57,
  },
  {
    id: 11,
    imgSrc: '/headphones-1.png',
    productName: 'Wireless Foldable Bluetooth Headphones',
    productPrice: 40,
  },
  {
    id: 12,
    imgSrc: '/headphones-2.png',
    productName: 'Foldable Wireless Bluetooth Headset',
    productPrice: 52,
  },
  {
    id: 13,
    imgSrc: '/mouse.png',
    productName: 'Portable Wireless Gaming Mouse',
    productPrice: 30,
  },
  {
    id: 14,
    imgSrc: '/keyboard.png',
    productName: 'Portable Wireless Keyboard',
    productPrice: 80,
  },
  {
    id: 15,
    imgSrc: '/portable-monitor.png',
    productName: 'Wireless Monitor HD Resolution',
    productPrice: 140,
  },
  {
    id: 16,
    imgSrc: '/power-bank.png',
    productName: 'Portable Power Bank Charger',
    productPrice: 90,
  },
];

type Product = {
  id: number;
  imgSrc: string | null;
  productName: string | null;
  productPrice: string | null;
};

export const getProductsInsecure = cache(async () => {
  // eslint-disable-next-line @typescript-eslint/no-shadow
  const products = await sql<Product[]>`
    SELECT
      *
    FROM
      products
  `;
  return products;
});

export default function getProduct(id: number) {
  return products.find((product) => product.id === id);
}
